### ISSUE TITLE
header and borderline

### ISSUE THREAD

**Issue by GuangluWu** [dogwaddle/obsidian-gastown-theme.md#2]
Hi @dogwaddle 

I like your theme in obsidian and use it for several days. Only one tiny thing I would suggest to improve: view header.

It looks like a block over float on the header which is particularly obvious when the section is inactive as shown in the image below:

<img width="791" alt="Screenshot 2020-05-31 at 10 28 03" src="https://user-images.githubusercontent.com/63955311/83349191-d6727280-a32a-11ea-9597-e83a994b4865.png">

Also, It would be more intuitive to set the borderline of the active header to 3px and inactive to 1px.

G

**Comment by dogwaddle** [comment]
@GuangluWu I didn't see it in my file. But I also haven't updated the GitHub .css file since v5.0. I went ahead and added my current CSS file. Let me know if it is still there and I'm just blind and I'll take another look.

**Comment by GuangluWu** [comment]
@dogwaddle The shadow disappears in the new version which is great. But head container still overlaps with the border-bottom.

I add a height attribute of 36px into the .view-header-title-container and solve the problem. If the height is not there, a default value of 40px was taken in my Mac OS. 36px is just right. 
```
.view-header-title-container:after {
background: white !important;
height: 36px;
}
```
Thank you! Great theme.
